# Number of ES nodes (pods) deployed on the cluster
replicaCount: 3

# initContainers specific configurations
initContainers:
  repository: busybox
  tag: latest
  pullPolicy: Always

# Elasticsearch specific configurations
elasticsearch:
  clusterName: elasticsearch-on-k8s
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.13.2
    pullPolicy: IfNotPresent
  ports:
    http: 9200
    transport: 9300
  resources:
    master:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    client:
      requests:
        memory: "1Gi"
        cpu: "0.5"
      limits:
        memory: "2Gi"
        cpu: "1"
    data:
      requests:
        memory: "1Gi"
        cpu: "0.5"
      limits:
        memory: "2Gi"
        cpu: "1"
  storage:
    size: 5Gi
    className: gp2 # This assumes Storage class used is gp2 on EKS. Update this if this is otherwise
  volumeMounts:
    mountPath: /usr/share/elasticsearch/data
  appName: elasticsearch
  serviceAccount:
    name: default

