# Configmap to store Elasticsearch cluster configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-elasticsearch-config
data:
  elasticsearch.yml: |-
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    node.name: elasticsearch-on-k8s
    network.host: 0.0.0.0
    node.roles: [ master, data, ingest ]
    discovery.type: single-node

    xpack.security.enabled: "false"
    xpack.security.http.ssl.enabled: "false"
    xpack.security.transport.ssl.enabled: "false"
    xpack.security.transport.ssl.verification_mode: none
