# Pod disruption budget to handle resiliency
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-elasticsearch-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.appName }}
