apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-busybox
  labels:
    app: {{ .Values.elasticsearch.appName }}
spec:
  containers:
  - name: busybox
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
      - "apk update && apk add curl && sleep infinity"
  restartPolicy: Never

