# Configmap to store Elasticsearch cluster configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-elasticsearch-config
data:
  elasticsearch.yml: |-
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    network.host: 0.0.0.0

    xpack.security.enabled: "false"
    xpack.security.http.ssl.enabled: "false"
    xpack.security.transport.ssl.enabled: "false"
    xpack.security.transport.ssl.verification_mode: none

    xpack.monitoring.collection.enabled: "true"
