# Network Policy to control accessibility of Elasticsearch pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-elasticsearch-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.elasticsearch.appName }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.elasticsearch.appName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.elasticsearch.appName }}-es-client
    ports:
    - protocol: TCP
      port: {{ .Values.elasticsearch.ports.http }}
    - protocol: TCP
      port: {{ .Values.elasticsearch.ports.transport }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.elasticsearch.appName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.elasticsearch.appName }}-es-client
    ports:
    - protocol: TCP
      port: {{ .Values.elasticsearch.ports.http }}
    - protocol: TCP
      port: {{ .Values.elasticsearch.ports.transport }}
